language: php
php:
  - '7.3'
  - nightly
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
  - composer install
script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests
